# Generated by Django 3.2.8 on 2021-11-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='backend',
            new_name='backend_name',
        ),
    ]
